= riff is for functions

As announced during Wednesday's keynote at SpringOne, `riff` provides developers with a service for executing Functions in response to Events. For more details, please see this presentation here link:README.adoc[<LINK TO BE PROVIDED AFTER WEDNESDAY KEYNOTE>]

== Key takeaways
After completing this lab, you will be familiar with the following features:

* **Portable & Kubernetes-native**: How to get `riff` up and running locally using `minikube`. To get `riff` running on any Kubernetes cluster either on-premise or in the cloud, please visit: link:https://github.com/projectriff/riff[`riff's` Github repo]
* **Polyglot**: How to deploy functions written in Java, NodeJS, Python and Shell. Said functions can support HTTP, gRPC or stdio
* **Event streaming**: How to pubish messages to `riff's` Kafka broker from the outside world
* **Scalability**: Scale from 0 to 1, from 1 to N and, eventually, back to 0

== Initial setup: Do this only once

==== Clone this Github repo

[source, bash]
----
git clone https://github.com/Pivotal-Field-Engineering/riff-in-a-nutshell.git
----

==== Start Minikube

CAUTION: There have been some DNS issues reported for Minikube v0.24, we suggest using v0.23 until this has been resolved

For Minikube, we recommend at least 4GB of memory:

[source, bash]
----
minikube start --memory=4096
----

==== Initialize Helm

Helm is comprised of 2 components: one is the client (helm) the other is the server component (tiller). The helm client runs on your local machine and can be installed using the instructions found https://github.com/kubernetes/helm/blob/master/README.md#install[here]

Once you have the helm client installed you can install the server component.

[source, bash]
----
helm init
----

NOTE: To verify that the tiller pod has started execute the following command: `kubectl get pod --namespace kube-system -l app=helm` and you should see the `tiller` pod running.


== Install `riff's` Helm Chart

This helm chart deploys `riff` and its required services to a Kubernetes Cluster.

===== Add the riff repository to your helm environment

Run the following commands to add the repository:

[source, bash]
----
helm repo add riffrepo https://riff-charts.storage.googleapis.com
helm repo update
----

Run the following command to see that the `riff` chart is available:

[source, bash]
----
helm search riff
----

==== To start from scratch, tear it all down, in case there is an existing installation

[source, bash]
----
helm delete demo --purge
----

==== Monitor the installation
Get ready to monitor the `riff` resources that will get created in your cluster. You can see them all using:

[source, bash]
----
watch kubectl get svc,deployments,pods,functions,topics
----

==== Install riff on MiniKube

For `NodePort` service types (e.g. running on Minikube) configure the httpGateway to use `NodePort`:

[source, bash]
----
helm install riffrepo/riff --name demo --set httpGateway.service.type=NodePort
----


== [[samples]]Labs

Once you get `riff` running, you can try one or more of the following functions:

* HTTP
  - link:samples/java/greeter/README.adoc[greeter: Java function]
  - link:samples/node/square/README.adoc[square: NodeJS function]
* gRPC
  - link:samples/python/uppercase/README.adoc[uppercase: Python function]
* stdio
  - link:samples/shell/echo/README.adoc[echo: Shell function]
