= uppercase

Click on the link below to view the function code:

[horizontal]
*Language*:: Python
*Function*:: https://github.com/projectriff/riff/blob/master/samples/python/uppercase/py/func.py[func.py]
*Protocol*:: gRPC
*Input*:: greetings

=== Monitor details of `riff's` functions, topics and pods in `minikube`
Open new shell window or tab and execute this command. We will refer to this as the **__monitoring window__**

[source, bash]
----
watch kubectl get deployments,pods,functions,topics
----

=== Delete the function

This allows you to start from scratch in case someone has already completed this lab

```
./riff delete -n uppercase
```

=== Build the image
Here is the supporting link:Dockerfile[Dockerfile]

```
eval $(minikube docker-env)
pushd samples/python/uppercase/ ; ./dockerize ; popd
```

=== Create the Function and Topic(s)
Here is link:uppercase.yaml[the YAML file] that creates the input topic as well as the function

```
./riff apply -f samples/python/uppercase
```
Switch to the **__monitoring window__** to check that the deployment, function(s) and topic(s) have been created

=== Tail the Sidecar Log

```
while sleep 1; do ./riff logs -n uppercase -t; done
```

=== Publish a Message to the Input Topic

```
./publish greetings HiSpringOne 100
```

